### ISSUE TITLE
[Bug] Build File Issue

### ISSUE THREAD

**Issue by Sudhakar555** [creativetimofficial/paper-dashboard-react#20] opened 2020-09-25 06:09 UTC
### Version
Yes
### Reproduction link
https://github.com/Sudhakar555/Dashboard-Covid-SpineBiz
### Operating System
Windows 10 
### Device
Lenovo Desktop
### Browser & Version
Chrome  85.0.4183.121
### Steps to reproduce
1. Build the file using npm run build
2. Try to deploy anywhere. (Git, NEtlify, Heroku, Express)
### What is expected?
Build File Deployment
### What is actually happening?
Build file not building correctly.

---
### Additional comments
Error 1 : index.js:4 DOMException: Failed to execute 'replaceState' on 'History': A history state object with URL 'file:///D:/admin/dashboard' cannot be created in a document with origin 'null' and URL 'file:///D:/Sudhakar/New%20folder/Covid-Dashboard/public/index.html'.

Error 2 : Access to internal resource at 'file:///D:/Sudhakar/New%20folder/Covid-Dashboard/public/manifest.json' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, chrome-untrusted, https.

Error 3 : Cannot GET /admin/dashboard (Running in Express Server)

I tried all the possible solutions but nothing worked.

**Comment by einazare** [comment] 2020-09-25 07:40
Hello there, @Sudhakar555 ,

Please make a video with the following:

* Download the product
* Unzip the product
* Open terminal and cd into the project
* Run node -v
* Run npm -v
* Make sure you have `serve` installed globally
* Go inside `package.json` file and delete the homepage prop
* Run `npm install`
* Run `npm run build`
* Run `serve -s build`
* Showcase the issue

We've done all of the above and everything worked as expected.
Also, please stop opening more and more issues. From what I can tell, all the issues you have opened are actually issues from your own code and not ours. So please, if you want, you can continue the discussion on one of the issues already opened, or you can ask for help on StackOverflow or on our special dedicated custom development page here: https://services.creative-tim.com/?ref=ct-footer

I will wait for the mentioned video, and you will see, that the issues are not from the product itself. After that, or in 5 days, I will close this issue. I am very sorry, but the issue is not from our product.

Best,
Manu

**Closed as completed** 2021-03-23 13:50 UTC
